
version: 2

models:
  - name: weather
    description: "A starter dbt model"
    columns:
      - name: station
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null