dbt_demo:
  outputs:
    dev:
      dremio_space: datalake
      dremio_space_folder: no_schema
      object_storage_path: no_schema
      object_storage_source: bucket
      password: admintest1
      port: 9047
      software_host: localhost
      threads: 1
      type: dremio
      use_ssl: false
      user: test
  target: dev
